<?xml version='1.0' encoding='UTF-8'?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>demo-books</artifactId>
    <version>1.0.0</version>
    <name>Books Demo</name>
    <description>
        A simple web application that retrieves a large set of books from an H2 in-memory database and returns a random
        one, implemented across multiple platforms.
    </description>

    <properties>
        <maven.enforcer.plugin.version>3.5.0</maven.enforcer.plugin.version>
        <required.maven.version>3.6.3</required.maven.version>
    </properties>

    <modules>
        <module>micronaut-books-demo</module>
        <module>spring-boot-books-demo</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>${maven.enforcer.plugin.version}</version>
                <executions>
                    <execution>
                        <id>enforce-maven</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireMavenVersion>
                                    <version>${required.maven.version}</version>
                                </requireMavenVersion>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
